require "rake/testtask"
require "rubocop/rake_task"

Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList["test/unit/**/*_test.rb"]
  t.verbose = true
end

Rake::TestTask.new(:integration) do |t|
  t.test_files = FileList["test/integration/**/*_test.rb"]
end

RuboCop::RakeTask.new
